### ISSUE TITLE
[Feature Request] Hardness multiplier

### ISSUE THREAD

**Issue by whichonespink44** [Ellpeck/MiningTweaks#2]
It would be great to have a hardness multiplier which modifies the hardness of all registered blocks.

It could be applied before the 'hardness' and 'mininglevels' settings are applied so that folks can still specify hardness values for specific blocks.

I've submitted PR https://github.com/Ellpeck/MiningTweaks/pull/1 for your review.

**Comment by Ellpeck** [comment]
To be discussed in the Pull Request.
